spring:
  application.name: k8s-test
  cloud.kubernetes.reload.enabled: true

server:
  port: 8080

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

app:
  title: "TEST APPLICATION TAKEN FROM YAML FILE"